### ISSUE TITLE
terminating container continues to accept input events

### ISSUE THREAD

**Issue by markfisher** [projectriff/function-sidecar#30]
when the pod enters the terminating state we should be shutting down the consumer then completing in-flight processing, but after a `kubectl delete function ...` command continuing to send events to the function's input topic keeps it active as a consumer even while the pod state shows "terminating".

**Comment by jldec** [comment]
suggest perhaps moving this to 0.0.3

**Comment by markfisher** [comment]
not sure if this is happening anymore, but I'm moving to 0.0.4 where we can verify and either fix or close this issue as no longer relevant

**Comment by jldec** [comment]
moved to 0.0.5 :)

**Comment by glyn** [comment]
Certainly the behaviour has changed quite a lot since this issue was raised, so I'd vote for closing the issue unless there is evidence it is still a problem.

**Comment by ericbottard** [comment]
This issue was moved to projectriff/riff#327
