### ISSUE TITLE
http dispatcher should not block

### ISSUE THREAD

**Issue by jldec** [projectriff/function-sidecar#37]
While working on https://github.com/projectriff/node-function-invoker/pull/9 it appears that the http dispatcher is blocking, and not allowing concurrent invocations to happen in one instance.

This prevents async http functions from operating concurrently, forcing riff to scale out when async http functions are idle, waiting for io, rather than sending more requests to the same instance.

**Comment by markfisher** [comment]
@ericbottard I think we can probably remove the sync "wrapper" and just have the HTTP dispatcher handle each request/response (including header propagation) within a goroutine. WDYT?
