### ISSUE TITLE
publish event metrics

### ISSUE THREAD

**Issue by markfisher** [projectriff/function-sidecar#41]
this is a prerequisite for https://github.com/projectriff/function-controller/issues/29 and https://github.com/projectriff/riff/issues/220

this will allow a listener (such as the `function-controller`) to keep track of producer and consumer throughput

should also publish consumer lifecycle events (when the actual event consumer is activated/deactivated) so that function-controller scaling can be more accurate

**Comment by ericbottard** [comment]
Closing this particular issue, without copying as it is now tracked in `riff` repo
