### ISSUE TITLE
Retry limit for function errors?

### ISSUE THREAD

**Issue by dsyer** [projectriff/function-sidecar#52]
When the sidecar sends a gRPC stream it fails  with a continuous stream of logs (apparently infinite):

```
Error receiving message from function: rpc error: code = Unknown desc =
Error receiving message from function: rpc error: code = Unknown desc =
Error receiving message from function: rpc error: code = Unknown desc =
...
```

The function invoker is failing (but only logging it once, strangely), but the sidecar goes on spitting out empty failure logs forever, and really it has no hope of ever succeeding.

**Comment by ericbottard** [comment]
This issue was moved to projectriff/riff#324
